baseURL                   = "http://javadude.com"
builddrafts                = false
languageCode               = "en-US"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 10

theme                      = "allinone"
title                      = "JavaDude.com"

[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Articles"
    weight                 = -180
    identifier             = "posts"
    url                    = "categories/articles/"  

  [[menu.main]]
    name                   = "Videos"
    weight                 = -200
    identifier             = "videos"
    url                    = "categories/videos/"  

  [[menu.main]]
    name                   = "Tools"
    weight                 = -160
    identifier             = "tools"
    url                    = "categories/tools/"  

  [[menu.main]]
    name                   = "Publications"
    weight                 = -110
    identifier             = "publications"
    url                    = "publications/" 

  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"  

 

[params]
  faviconfile              = "img/favicon.ico"               # from static/
  avatar                   = "img/scott.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Scott Stanchfield"
  description              = ["Developer", "Teacher", "Tinkerer"]           # appears in the site header when set to a non-empty string
  welcome_head             = "JavaDude.com"
  welcome_word             = "No Day But Today"

  latestpostscount         = 10                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = true                         # if true, don't show "<x> minutes read" in posts

  # slides
#  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPath            = "static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "scott@javadude.com"
  github                   = "//github.com/javadude"
  facebook                 = "//facebook.com/scott.stanchfield"
  include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  #googleAnalytics          = "your-google-analytic-id"